# Generated by Django 2.2.16 on 2022-10-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
